file.name <- "household_power_consumption.txt"
data <- read.table(file.name, header=TRUE, sep=";", na.string="?")
data$dateTime <- do.call(paste, c(data[c("Date", "Time")], sep = " "))
data$dateTime <- strptime(data$dateTime, format="%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
dataSubs <- subset(data, Date == "2007-02-01" | Date == "2007-02-02")
png("plot4.png", height=480, width=480)
par(mfrow=c(2,2))
plot(dataSubs$dateTime,dataSubs$Global_active_power,pch="",xlab="",ylab="Global Active Power")
lines(dataSubs$dateTime,dataSubs$Global_active_power)
plot(dataSubs$dateTime,dataSubs$Voltage,xlab="datetime",ylab="Voltage",pch="")
lines(dataSubs$dateTime,dataSubs$Voltage)
plot(dataSubs$dateTime,dataSubs$Sub_metering_1,pch="", ylab="Energy sub metering",xlab="")
points(dataSubs$dateTime,dataSubs$Sub_metering_2, col="red",pch="")
points(dataSubs$dateTime,dataSubs$Sub_metering_1, col="blue",pch="")
lines(dataSubs$dateTime,dataSubs$Sub_metering_1)
lines(dataSubs$dateTime,dataSubs$Sub_metering_2, col = "red")
lines(dataSubs$dateTime,dataSubs$Sub_metering_3,col="blue")
legend("topright",lwd=2, bty="n", col = c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(dataSubs$dateTime,dataSubs$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",pch="")
lines(dataSubs$dateTime,dataSubs$Global_reactive_power,lwd=0.5)
dev.off()